### ISSUE TITLE
Magic Storage - Extra : All recipes disappear

### ISSUE THREAD

**Issue by Estions** [Ishigh1/RecursiveCraft#1]
When using Magic Storage - Extra upon first opening of the crafting terminal all recipes show up, but after a certain number of crafts (the number seems random, but for me normally occurred after 2-3 crafts) all recipes disappear. This issue is solved by closing the terminal and opening it again or sometimes (very unreliably) by removing a random crafting station from it's slot and placing it back it. 
At first the recursion threshold was at -1 (so, infinite as I understand), yet after setting it to 0 (the same as vanilla I presume) the issue was still there and only by uninstalling RecursiveCraft was the issue fixed.

**Comment by ExterminatorX99** [comment]
This is a Magic Storage issue.
Post it there for me [MagicStorageExtra](https://github.com/ExterminatorX99/MagicStorage)

**Comment by Estions** [comment]
Okay, thank you
