### ISSUE TITLE
Default Config FPS Issue

### ISSUE THREAD

**Issue by Ultrasucc** [Ishigh1/RecursiveCraft#4]
As is currently, the default value of -1 (infinite) depth search is horrible for the framerate. Every time I open my inventory or any other menu, it lags out for a second or two, and then returns back to normal, until I close that same UI.
While I like the concept of the mod, using a larger modpack (i.e. multiple large content mods) causes this to happen. Setting the search depth to 3 removes any issues (at least for my CPU - i5 9600kf). At 4 there's a good 0.5s lag, and anything beyond that is impossible to play with.
I believe it would be best to set the default to 0, just in case.
Another thing that I noticed is that while my inventory is open with depth of 3, there's a significant fps drop (60->30ish).
I think that I should definitely point these issues out, at least for me, in hopes of getting them fixed.
Perhaps leave a setting where people are able to choose when the recursive craft is enabled? Such as MSExtended? Or only when near a station? I'm not sure how this behavior applies to no mods (or a few small ones), so I'm unable to give any feedback to this specific set of variables, though I'm sure that most people play with many mods regardless, much like me, and if they forget to change the config, they could possibly crash their game should their CPU be not strong enough.

Edit: The mod throws an index out of bounds error when using on multiplayer. Not sure if it's directly connected to multiplayer or a different issue altogether.

**Comment by Ishigh1** [comment]
I play with only few mods so I never really saw the difference, and default to 0 would be the same as not installing the mod, so it's not great either if they don't change it
I'll work on the performances though
For the index out of bound, it seems that an other mod is causing that because it works fine on my side

**Comment by Ishigh1** [comment]
1.5 should have increased the performances, does it still heavily impact the FPS ?

**Comment by Ultrasucc** [comment]
Haven't gotten around to testing it yet, I'll post a response in a couple of days -- exams and finals. This FPS issue is more than likely due to the tons of recipes that feed back into themselves (AoMM, LadyFluffyPanda's, ExtendedCrafting (or whatever the name was, I keep forgetting it), as you could assume what sort of a mess this could cause. Here's the modlist, if you're interested in what could cause that out of bounds error:
`[
  "_ColoredDamageTypes",
  "AFKPETS",
  "AmuletOfManyMinions",
  "AnglerPlusPlus",
  "AutoReroll",
  "AutoTrash",
  "Boss_Unconsumables",
  "BossChecklist",
  "BossCursor",
  "BotanyPlus",
  "bowmod",
  "Buffaria",
  "CalamemeMagnumUnleashed",
  "CalamityMod",
  "CalamityModMusic",
  "CalValEX",
  "Camping",
  "Census",
  "CensusSupport",
  "ClamExtraMusic",
  "DisableCorruptionSpread",
  "DynamicSummons",
  "EasierBossLoot",
  "EchoesoftheAncients",
  "ExtensibleInventory",
  "Fargowiltas",
  "FargowiltasMusic",
  "FargowiltasSouls",
  "FargowiltasSoulsDLC",
  "Fishing3",
  "FunctionalBlockSwap",
  "GoldensMisc",
  "HamstarHelpers",
  "ReducedGrinding",
  "JoostMod",
  "LansAutoJoinTeam",
  "Leveled",
  "MagicStorageExtra",
  "MaxStackExtra",
  "MilitaryMod",
  "MiniBossNPC",
  "MinionCrits",
  "MoreAccessories",
  "MoreEmblems",
  "NoMoreTombs",
  "OneStopNPCShop",
  "OreSeeds",
  "PlentifulOres",
  "RecipeBrowser",
  "ShopExpander",
  "ShorterRespawn",
  "SmartDoors",
  "SpiritMod",
  "Split",
  "StarterClasses",
  "StopDying",
  "StormDiversSuggestions",
  "SummonersAssociation",
  "TerrariumArcana",
  "tMusicPlayer",
  "TysSimplifiedSummoning",
  "UnclutteredProjectiles",
  "VeinMiner",
  "WebmilioCommons",
  "Widgets",
  "WingSlot",
  "WingsStatsAndHookStats",
  "WMITF",
  "ZLegendarys",
  "EAMusic",
  "ElementsAwoken",
  "PreHMTeleportation",
  "LansUnlimitedBuffSlots",
  "Luiafk",
  "SOTS",
  "PylonNPC",
  "EndlessCrafting",
  "LadyFluffyPandasMod",
  "GemToGem",
  "PboneUtils",
  "UsefulNPCs",
  "TenebraeMod",
  "VitalityMod"
]`

**Comment by Ishigh1** [comment]
Out of bounds should be solved with 1.6
