### ISSUE TITLE
Mod crashes server sometimes

### ISSUE THREAD

**Issue by Sciti** [Ishigh1/RecursiveCraft#7]
Got this error message, expierence and classes incompabile? People in discord told me to report this issue to RecirsiveCraft devs

> Server hung for more than 10 seconds:
>    at Microsoft.Win32.Win32Native.WriteFile(SafeFileHandle handle, Byte* bytes, Int32 numBytesToWrite, Int32& numBytesWritten, IntPtr mustBeZero)
>    at System.IO.__ConsoleStream.WriteFileNative(SafeFileHandle hFile, Byte[] bytes, Int32 offset, Int32 count, Boolean useFileAPIs)
>    at System.IO.__ConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
>    at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
>    at System.IO.TextWriter.WriteLine(String value)
>    at System.IO.TextWriter.SyncTextWriter.WriteLine(String value)
>    at System.Console.WriteLine(String value)
>    at ExperienceAndClasses.ExperienceAndClasses.HandlePacket(BinaryReader reader, Int32 whoAmI) in ExperienceAndClasses.cs:line 641
>    at Terraria.ModLoader.ModNet.HandleModPacket(BinaryReader reader, Int32 whoAmI, Int32 length)
>    at Terraria.MessageBuffer.GetData(Int32 start, Int32 length, Int32& messageType)
>    at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
>    at Terraria.Netplay.<>c.<ServerLoop>b__46_2()
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
>    at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
>    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
>    at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
>    at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
>    at System.Threading.Tasks.Task.InternalRunSynchronously(TaskScheduler scheduler, Boolean waitForCompletion)
>    at Terraria.Netplay.OnUpdate()
>    at Terraria.Main.DoUpdate(GameTime gameTime)
>    at DMD<Terraria.Main::Update>(Main this, GameTime gameTime)
>    at Trampoline<Terraria.Main::Update>?43386478(Main , GameTime )
>    at RecursiveCraft.RecursiveCraft.ApplyKey(orig_Update orig, Main self, GameTime gameTime) in RecursiveCraft.cs:line 187
>    at Hook<Terraria.Main::Update>?14599532(Main , GameTime )
>    at Terraria.Main.DedServ()
>    at Terraria.Program.LaunchGame_()
>    at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
>    at Terraria.WindowsLaunch.Main(String[] args)

**Comment by Ishigh1** [comment]
The issue doesn't seems to be from my side, try disabling some mods to find the buggy one
